/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zlib_compress_Czlib */

#ifndef _Included_org_zlib_compress_Czlib
#define _Included_org_zlib_compress_Czlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zlib_compress_Czlib
 * Method:    compress
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zlib_compress_Czlib_compress
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_zlib_compress_Czlib
 * Method:    deCompress
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zlib_compress_Czlib_deCompress
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
